name: NEXT Deploy
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master
        with:
          ref: main

      - name: Install Dependencies
        run: |
          npm install

      # 환경 변수 파일을 생성.
      - name: Generate Environment Variables File for Production
        run: |
          echo "NEXT_PUBLIC_GOOGLE_MAP_KEY=$NEXT_PUBLIC_GOOGLE_MAP_KEY" >> .env.production
          echo "NEXT_PUBLIC_TMAP_KEY=$NEXT_PUBLIC_TMAP_KEY" >> .env.production
          echo "NEXT_PUBLIC_AWS_S3=$NEXT_PUBLIC_AWS_S3" >> .env.production
          echo "NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL" >> .env.production
          echo "NEXT_PUBLIC_KAKAO_APP_KEY=$NEXT_PUBLIC_KAKAO_APP_KEY" >> .env.production
          echo "NEXT_PUBLIC_KAKAO_REDIRECT_URI=$NEXT_PUBLIC_KAKAO_REDIRECT_URI" >> .env.production

        env:
          NEXT_PUBLIC_GOOGLE_MAP_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAP_KEY }}
          NEXT_PUBLIC_TMAP_KEY: ${{ secrets.NEXT_PUBLIC_TMAP_KEY }}
          NEXT_PUBLIC_AWS_S3: ${{ secrets.NEXT_PUBLIC_AWS_S3 }}
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          NEXT_NEXT_PUBLIC_KAKAO_APP_KEY: ${{ secrets.NEXT_NEXT_PUBLIC_KAKAO_APP_KEY }}
          NEXT_PUBLIC_KAKAO_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_KAKAO_REDIRECT_URI }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy Next.js app
        run: |
          npm run deploy
